[theme]
base="dark"
primaryColor="#00f2fe"
backgroundColor="#000000"
secondaryBackgroundColor="rgba(255, 255, 255, 0.05)"
textColor="#e2e8f0"
font="sans serif"

[client]
# Hides the Streamlit toolbar ("hamburger menu", deploy button, etc.)
toolbarMode = "minimal"
showErrorDetails = false
